/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'id', 'ipAddress', 'metadata', 'resourceId', 'resourceType', 'userId'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare ipAddress: string | null
  @column()
  declare metadata: any | null
  @column()
  declare resourceId: string | null
  @column()
  declare resourceType: string | null
  @column()
  declare userId: number | null
}

export class ChatMessageSchema extends BaseModel {
  static $columns = ['chatSessionId', 'content', 'createdAt', 'id', 'metadata', 'role', 'sources', 'thinkingContent'] as const
  $columns = ChatMessageSchema.$columns
  @column()
  declare chatSessionId: number
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: any | null
  @column()
  declare role: string
  @column()
  declare sources: any | null
  @column()
  declare thinkingContent: string | null
}

export class ChatSessionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'metadata', 'modelName', 'title', 'updatedAt', 'userId'] as const
  $columns = ChatSessionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: any | null
  @column()
  declare modelName: string
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class CommunicationTreeSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'incidentId', 'name', 'treeData', 'type', 'updatedAt'] as const
  $columns = CommunicationTreeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare incidentId: number | null
  @column()
  declare name: string
  @column()
  declare treeData: any
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EssentialFunctionSchema extends BaseModel {
  static $columns = ['alternatePersonnel', 'createdAt', 'id', 'incidentId', 'name', 'primaryPersonnel', 'priority', 'procedures', 'recoveryTimeObjective', 'status', 'updatedAt'] as const
  $columns = EssentialFunctionSchema.$columns
  @column()
  declare alternatePersonnel: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare incidentId: number
  @column()
  declare name: string
  @column()
  declare primaryPersonnel: any | null
  @column()
  declare priority: number
  @column()
  declare procedures: any | null
  @column()
  declare recoveryTimeObjective: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GeofenceSchema extends BaseModel {
  static $columns = ['active', 'color', 'createdAt', 'description', 'geometry', 'id', 'incidentId', 'name', 'type', 'updatedAt'] as const
  $columns = GeofenceSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare geometry: any
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare incidentId: number | null
  @column()
  declare name: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class IcsActivityLogSchema extends BaseModel {
  static $columns = ['activity', 'actorId', 'category', 'correctsId', 'createdAt', 'id', 'incidentId', 'loggedAt', 'source'] as const
  $columns = IcsActivityLogSchema.$columns
  @column()
  declare activity: string
  @column()
  declare actorId: number | null
  @column()
  declare category: string
  @column()
  declare correctsId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare incidentId: number
  @column.dateTime()
  declare loggedAt: DateTime
  @column()
  declare source: string
}

export class IncidentSchema extends BaseModel {
  static $columns = ['closedAt', 'createdAt', 'declaredAt', 'description', 'iapPeriod', 'id', 'incidentCommanderId', 'name', 'status', 'type', 'updatedAt'] as const
  $columns = IncidentSchema.$columns
  @column.dateTime()
  declare closedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare declaredAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare iapPeriod: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare incidentCommanderId: number | null
  @column()
  declare name: string
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InstalledResourceSchema extends BaseModel {
  static $columns = ['createdAt', 'downloadUrl', 'errorMessage', 'filePath', 'fileSize', 'id', 'knowledgeSourceId', 'metadata', 'name', 'ragEnabled', 'resourceType', 'status', 'updatedAt'] as const
  $columns = InstalledResourceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare downloadUrl: string | null
  @column()
  declare errorMessage: string | null
  @column()
  declare filePath: string | null
  @column()
  declare fileSize: bigint | number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare knowledgeSourceId: number | null
  @column()
  declare metadata: any | null
  @column()
  declare name: string
  @column()
  declare ragEnabled: boolean
  @column()
  declare resourceType: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class KnowledgeSourceSchema extends BaseModel {
  static $columns = ['chunkCount', 'completedAt', 'createdAt', 'errorMessage', 'filePath', 'fileSize', 'id', 'metadata', 'mimeType', 'name', 'sourceType', 'status', 'updatedAt'] as const
  $columns = KnowledgeSourceSchema.$columns
  @column()
  declare chunkCount: number
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare errorMessage: string | null
  @column()
  declare filePath: string | null
  @column()
  declare fileSize: bigint | number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: any | null
  @column()
  declare mimeType: string | null
  @column()
  declare name: string
  @column()
  declare sourceType: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class KvStoreSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'updatedAt', 'value'] as const
  $columns = KvStoreSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string | null
}

export class MeshMessageSchema extends BaseModel {
  static $columns = ['channel', 'content', 'createdAt', 'fromNode', 'id', 'isEmbedded', 'packetId', 'portNum', 'rawPayload', 'receivedAt', 'toNode', 'updatedAt'] as const
  $columns = MeshMessageSchema.$columns
  @column()
  declare channel: string
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fromNode: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isEmbedded: boolean
  @column()
  declare packetId: string
  @column()
  declare portNum: string
  @column()
  declare rawPayload: any | null
  @column.dateTime()
  declare receivedAt: DateTime
  @column()
  declare toNode: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MeshNodeSchema extends BaseModel {
  static $columns = ['altitude', 'batteryLevel', 'createdAt', 'hardwareModel', 'id', 'isOnline', 'lastHeardAt', 'latitude', 'longName', 'longitude', 'nodeId', 'shortName', 'snr', 'updatedAt'] as const
  $columns = MeshNodeSchema.$columns
  @column()
  declare altitude: number | null
  @column()
  declare batteryLevel: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare hardwareModel: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isOnline: boolean
  @column.dateTime()
  declare lastHeardAt: DateTime | null
  @column()
  declare latitude: number | null
  @column()
  declare longName: string | null
  @column()
  declare longitude: number | null
  @column()
  declare nodeId: string
  @column()
  declare shortName: string | null
  @column()
  declare snr: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ModelRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isDefault', 'modelName', 'options', 'roleName', 'systemPrompt', 'updatedAt'] as const
  $columns = ModelRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDefault: boolean
  @column()
  declare modelName: string
  @column()
  declare options: any | null
  @column()
  declare roleName: string
  @column()
  declare systemPrompt: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PersonnelStatusSchema extends BaseModel {
  static $columns = ['assignment', 'checkedInAt', 'checkedInVia', 'createdAt', 'id', 'incidentId', 'latitude', 'locationText', 'longitude', 'status', 'updatedAt', 'userId'] as const
  $columns = PersonnelStatusSchema.$columns
  @column()
  declare assignment: string | null
  @column.dateTime()
  declare checkedInAt: DateTime
  @column()
  declare checkedInVia: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare incidentId: number
  @column()
  declare latitude: string | null
  @column()
  declare locationText: string | null
  @column()
  declare longitude: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PromptTemplateSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'id', 'isActive', 'name', 'slug', 'template', 'updatedAt', 'variables', 'version'] as const
  $columns = PromptTemplateSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare template: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare variables: any | null
  @column()
  declare version: number
}

export class ResourceSchema extends BaseModel {
  static $columns = ['assignedIncidentId', 'createdAt', 'expiryDate', 'id', 'latitude', 'longitude', 'name', 'notes', 'quantity', 'status', 'type', 'updatedAt'] as const
  $columns = ResourceSchema.$columns
  @column()
  declare assignedIncidentId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare expiryDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: string | null
  @column()
  declare longitude: string | null
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare quantity: number
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RetrievalFeedbackSchema extends BaseModel {
  static $columns = ['chatMessageId', 'comment', 'createdAt', 'id', 'rating', 'sourceIds', 'userId'] as const
  $columns = RetrievalFeedbackSchema.$columns
  @column()
  declare chatMessageId: number
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rating: string
  @column()
  declare sourceIds: any | null
  @column()
  declare userId: number
}

export class ServiceSchema extends BaseModel {
  static $columns = ['config', 'containerName', 'createdAt', 'id', 'image', 'name', 'status', 'updatedAt'] as const
  $columns = ServiceSchema.$columns
  @column()
  declare config: any | null
  @column()
  declare containerName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare image: string
  @column()
  declare name: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ToolDefinitionSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'description', 'displayName', 'id', 'isBuiltin', 'isEnabled', 'minimumRole', 'name', 'parameters', 'requiresConfirmation', 'updatedAt'] as const
  $columns = ToolDefinitionSchema.$columns
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare displayName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isBuiltin: boolean
  @column()
  declare isEnabled: boolean
  @column()
  declare minimumRole: string
  @column()
  declare name: string
  @column()
  declare parameters: any
  @column()
  declare requiresConfirmation: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
